import os
import shutil
import sys
from os.path import isfile, join


def delete_files(file_list):
    for file in file_list:
        if os.path.exists(file):
            if isfile(file):
                os.remove(file)
            else:
                shutil.rmtree(file)


if __name__ == "__main__":
    # Light clean up, delete all files generated by package building
    files = ['Pytonium.egg-info', 'PytoniumTests/cache', 'build', '_skbuild', 'Pytonium/bin.zip',
             'Pytonium/src/pytonium.cpp', 'Pytonium/src.cpython-311-x86_64-linux-gnu.so']

    delete_files(files)

    if len(sys.argv) > 1 and sys.argv[1] == 'all':
        # Heavy clean up, delete all generated files, also the cmake ones.
        files = ['Pytonium/bin', 'Pytonium/src/pytonium_library',
                 'Pytonium/src/include', 'Pytonium/src/lib']

        delete_files(files)
