class Pytonium:
    def __init__(self) -> None: ...
    def pytonium_subprocess_path(cls) -> None: ...
    def initialize(self, start_url: str, init_width: int, init_height: int) -> None: ...
    def return_value_to_javascript(self, message_id: int, value) -> None: ...
    def execute_javascript(self, code: str) -> None: ...
    def bind_function_to_javascript(self, function_to_bind: callable, name="", javascript_object="") -> None: ...
    def bind_functions_to_javascript(self, functions_to_bind: list[callable], names=[], javascript_object="") -> None: ...
    def bind_object_methods_to_javascript(self, obj: object, names=[], javascript_object="") -> None: ...
    def add_context_menu_entry(self, context_menu_entry_function: callable, display_name="", context_menu_namespace="") -> None: ...
    def add_context_menu_entries(self, context_menu_entry_functions: list[callable], display_names=[], context_menu_namespace="") -> None: ...
    def add_context_menu_entries_from_object(self, context_menu_entries_object: object, display_names=[], context_menu_namespace="") -> None: ...
    def set_context_menu_namespace(self, context_menu_namespace: str) -> None: ...
    def set_show_debug_context_menu(self, show: bool) -> None: ...
    def add_state_handler(self, state_handler: object, namespaces: list[str]) -> None: ...
    def shutdown(self) -> None: ...
    def is_running(self) -> None: ...

    def update_message_loop(self) -> None: ...
    def set_cache_path(self, path: str) -> None: ...
    def set_custom_icon_path(self, path: str) -> None: ...
    def load_url(self, url: str) -> None: ...
    def set_state(self, namespace: str, key: str, value: object) -> None: ...
    def generate_typescript_definitions(self, filename: str) -> None: ...
