class Pytonium:
    def __init__(self) -> None: ...
    def pytonium_subprocess_path(cls) -> None: ...
    def initialize(self, start_url: str, init_width: int, init_height: int) -> None: ...
    def return_value_to_javascript(self, message_id: int, value) -> None: ...
    def execute_javascript(self, code: str) -> None: ...
    def bind_function_to_javascript(self, name: str, func, javascript_object: str) -> None: ...
    def add_state_handler(self, state_handler: object, namespaces: list[str]) -> None: ...
    def shutdown(self) -> None: ...
    def is_running(self) -> None: ...
    def bind_object_methods_to_javascript(self, obj: object, javascript_object: str) -> None: ...
    def update_message_loop(self) -> None: ...
    def set_cache_path(self, path: str) -> None: ...
    def set_custom_icon_path(self, path: str) -> None: ...
    def load_url(self, url: str) -> None: ...
    def set_state(self, namespace: str, key: str, value: object) -> None: ...
    def generate_typescript_definitions(self, filename: str) -> None: ...
