from typing import Any, Callable, Optional, Sequence

class Pytonium:
    def __init__(self) -> None: ...

    @classmethod
    def pytonium_subprocess_path(cls) -> str: ...

    @classmethod
    def set_subprocess_path(cls, value: str) -> None: ...

    def initialize(self, start_url: str, init_width: int, init_height: int) -> None: ...
    def return_value_to_javascript(self, message_id: int, value: Any) -> None: ...
    def execute_javascript(self, code: str) -> None: ...

    def bind_function_to_javascript(
        self,
        function_to_bind: Callable[..., Any],
        name: str = "",
        javascript_object: str = "",
    ) -> None: ...

    def bind_functions_to_javascript(
        self,
        functions_to_bind: list[Callable[..., Any]],
        names: Optional[list[str]] = None,
        javascript_object: str = "",
    ) -> None: ...

    def bind_object_methods_to_javascript(
        self,
        obj: object,
        names: Optional[list[str]] = None,
        javascript_object: str = "",
    ) -> None: ...

    def add_context_menu_entry(
        self,
        context_menu_entry_function: Callable[..., Any],
        display_name: str = "",
        context_menu_namespace: str = "",
    ) -> None: ...

    def add_context_menu_entries(
        self,
        context_menu_entry_functions: list[Callable[..., Any]],
        display_names: Optional[list[str]] = None,
        context_menu_namespace: str = "",
    ) -> None: ...

    def add_context_menu_entries_from_object(
        self,
        context_menu_entries_object: object,
        display_names: Optional[list[str]] = None,
        context_menu_namespace: str = "",
    ) -> None: ...

    def add_state_handler(self, state_handler: object, namespaces: list[str]) -> None: ...
    def set_context_menu_namespace(self, context_menu_namespace: str) -> None: ...
    def set_show_debug_context_menu(self, show: bool) -> None: ...
    def create_browser(self, url: str, width: int, height: int, frameless: bool = False, icon_path: str = "") -> int: ...
    def close_browser(self) -> None: ...
    def get_browser_id(self) -> int: ...
    def shutdown(self) -> None: ...
    def is_running(self) -> bool: ...

    @classmethod
    def is_cef_initialized(cls) -> bool: ...
    def update_message_loop(self) -> None: ...
    def add_custom_scheme(self, scheme_identifier: str, scheme_content_root_folder: str) -> None: ...
    def add_mime_type_mapping(self, file_extension: str, mime_type: str) -> None: ...
    def set_cache_path(self, path: str) -> None: ...
    def set_custom_icon_path(self, path: str) -> None: ...
    def load_url(self, url: str) -> None: ...

    # Window control methods
    def set_frameless_window(self, frameless: bool) -> None: ...
    def set_osr_mode(self, osr: bool) -> None: ...
    def minimize_window(self) -> None: ...
    def maximize_window(self) -> None: ...
    def restore_window(self) -> None: ...
    def close_window(self) -> None: ...
    def is_maximized(self) -> bool: ...
    def drag_window(self, delta_x: int, delta_y: int) -> None: ...
    def get_window_position(self) -> tuple[int, int]: ...
    def set_window_position(self, x: int, y: int) -> None: ...
    def get_window_size(self) -> tuple[int, int]: ...
    def set_window_size(self, width: int, height: int) -> None: ...
    def resize_window(self, new_width: int, new_height: int, anchor: int = 0) -> None: ...

    def set_state(self, namespace: str, key: str, value: Any) -> None: ...
    def generate_typescript_definitions(self, filename: str) -> None: ...

    # Native window handle (Windows: HWND as int, Linux: X11 window ID)
    def get_native_window_handle(self) -> int: ...

    # Window event callbacks
    def on_title_change(self, callback: Callable[[str], None]) -> None: ...
    def on_address_change(self, callback: Callable[[str], None]) -> None: ...
    def on_fullscreen_change(self, callback: Callable[[bool], None]) -> None: ...
